version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development
  - package-ecosystem: npm
    directory: /packages/create-hx
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      create-hx-dependencies:
        patterns:
          - '*'
