import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));

export const repositoryRoot = resolve(scriptDirectory, '../..');
export const tutorialRoot = join(repositoryRoot, 'tutorials/nestjs-backend');

const generatedDirectory = 'tutorials/nestjs-backend/generated';
const generatedNotice =
  '<!-- AUTO-GENERATED by scripts/tutorial/generate-project-facts.mjs. DO NOT EDIT. -->';

function readRepositoryFile(path) {
  return readFileSync(join(repositoryRoot, path), 'utf8');
}

export function repositoryPath(path) {
  return join(repositoryRoot, path);
}

export function toPosix(path) {
  return path.split(sep).join('/');
}

export function walkFiles(directory, predicate = () => true) {
  if (!existsSync(directory)) return [];

  const files = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...walkFiles(path, predicate));
    else if (predicate(path)) files.push(path);
  }
  return files.sort();
}

function repositoryLink(path, label = path) {
  return `[${label}](../../../${path})`;
}

function generatedHeader(title, sources) {
  const sourceLinks = sources.map((source) => repositoryLink(source)).join('、');
  return `${generatedNotice}

# ${title}

> [返回生成内容目录](README.md) · [返回教程首页](../README.md)

本页由仓库源码自动生成，请勿手工修改。事实来源：${sourceLinks}。
`;
}

function escapeTableCell(value) {
  return String(value).replaceAll('|', '\\|').replaceAll('\n', '<br>');
}

function inlineCode(value) {
  return `\`${String(value).replaceAll('`', '\\`')}\``;
}

function renderGeneratedIndex() {
  return `${generatedNotice}

# 当前项目事实快照

> [返回教程首页](../README.md) · [查看维护说明](../maintenance/README.md)

这里保存可以直接从仓库代码确定的事实。运行 \`pnpm tutorial:generate\` 更新，运行 \`pnpm tutorial:check\` 检查是否漂移。

- [包管理与项目命令](commands.md)
- [环境变量](environment.md)
- [Docker Compose 服务](compose-services.md)
- [Prisma 数据模型与迁移](prisma-models.md)
- [NestJS 模块与 API 路由](api-routes.md)

这些页面只回答“当前代码是什么”，设计原因仍由人工维护的教程章节解释。
`;
}

function renderCommands() {
  const packageJson = JSON.parse(readRepositoryFile('package.json'));
  const scripts = Object.entries(packageJson.scripts ?? {});

  const rows = scripts
    .map(([name, command]) => `| ${inlineCode(`pnpm ${name}`)} | ${inlineCode(command)} |`)
    .join('\n');

  return `${generatedHeader('包管理与项目命令', ['package.json'])}
## 工具链约束

- Node.js：${inlineCode(packageJson.engines?.node ?? '未声明')}
- pnpm：${inlineCode(packageJson.engines?.pnpm ?? '未声明')}
- Package Manager：${inlineCode(packageJson.packageManager ?? '未声明')}

## Scripts

<!-- prettier-ignore -->
| 调用方式 | 实际命令 |
| --- | --- |
${rows}
`;
}

function parseEnvironmentExample() {
  const lines = readRepositoryFile('.env.example').split(/\r?\n/);
  const entries = [];
  let comments = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('#')) {
      comments.push(trimmed.slice(1).trim());
      continue;
    }
    if (!trimmed) {
      comments = [];
      continue;
    }

    const match = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
    if (!match) continue;
    entries.push({ name: match[1], value: match[2], description: comments.join(' ') });
    comments = [];
  }

  return entries;
}

function environmentSchemaKeys() {
  const source = readRepositoryFile('libs/platform/src/config/environment.ts');
  const objectStart = source.indexOf('.object({');
  const objectEnd = source.indexOf('\n  })', objectStart);
  if (objectStart < 0 || objectEnd < 0) {
    throw new Error('Cannot locate environmentSchema object in environment.ts.');
  }

  const objectSource = source.slice(objectStart, objectEnd);
  return [...objectSource.matchAll(/^ {4}([A-Z][A-Z0-9_]+):/gm)].map((match) => match[1]);
}

function validateEnvironmentCoverage(exampleEntries, schemaKeys) {
  const example = new Set(exampleEntries.map((entry) => entry.name));
  const schema = new Set(schemaKeys);
  const missingFromExample = [...schema].filter((key) => !example.has(key));
  const missingFromSchema = [...example].filter((key) => !schema.has(key));

  if (missingFromExample.length || missingFromSchema.length) {
    const details = [];
    if (missingFromExample.length) {
      details.push(`missing from .env.example: ${missingFromExample.join(', ')}`);
    }
    if (missingFromSchema.length) {
      details.push(`missing from environmentSchema: ${missingFromSchema.join(', ')}`);
    }
    throw new Error(`Environment documentation sources disagree (${details.join('; ')}).`);
  }
}

function environmentDisplayValue(name, value) {
  if (/SECRET|PASSWORD|TOKEN/.test(name)) {
    return value ? '<redacted>' : '<empty; inject securely when enabled>';
  }
  if (!value) return '<empty; optional or provider-dependent>';

  const sanitized = value.replace(/:\/\/([^:]+):([^@]+)@/, '://$1:***@');
  return sanitized;
}

function renderEnvironment() {
  const entries = parseEnvironmentExample();
  const schemaKeys = environmentSchemaKeys();
  validateEnvironmentCoverage(entries, schemaKeys);

  const rows = entries
    .map((entry) => {
      const value = environmentDisplayValue(entry.name, entry.value);
      return `| ${inlineCode(entry.name)} | ${inlineCode(value)} | ${escapeTableCell(entry.description || '—')} |`;
    })
    .join('\n');

  return `${generatedHeader('环境变量', [
    '.env.example',
    'libs/platform/src/config/environment.ts',
  ])}
生成器会校验 \`.env.example\` 与运行时 Zod Schema 的变量集合完全一致。敏感示例值和 URL 密码会被遮盖。

<!-- prettier-ignore -->
| 变量 | 本地示例/状态 | 邻近说明 |
| --- | --- | --- |
${rows}
`;
}

function sectionEntries(block, sectionName) {
  const lines = block.split(/\r?\n/);
  const sectionIndex = lines.findIndex((line) => line === `    ${sectionName}:`);
  if (sectionIndex < 0) return [];

  const entries = [];
  for (const line of lines.slice(sectionIndex + 1)) {
    if (line.trim() && !line.startsWith('      ')) break;
    const listItem = line.match(/^ {6}-\s+['"]?(.+?)['"]?\s*$/);
    if (listItem) entries.push(listItem[1].replace(/^['"]|['"]$/g, ''));
  }
  return entries;
}

function dependencyEntries(block) {
  const lines = block.split(/\r?\n/);
  const sectionIndex = lines.findIndex((line) => line === '    depends_on:');
  if (sectionIndex < 0) return [];

  const entries = [];
  for (const line of lines.slice(sectionIndex + 1)) {
    if (line.trim() && !line.startsWith('      ')) break;
    const listItem = line.match(/^ {6}-\s+([a-zA-Z0-9_-]+)\s*$/);
    const mapItem = line.match(/^ {6}([a-zA-Z0-9_-]+):/);
    if (listItem) entries.push(listItem[1]);
    else if (mapItem) entries.push(mapItem[1]);
  }
  return [...new Set(entries)];
}

function parseComposeServices() {
  const source = readRepositoryFile('docker-compose.yml');
  const lines = source.split(/\r?\n/);
  const servicesStart = lines.findIndex((line) => line === 'services:');
  if (servicesStart < 0) throw new Error('docker-compose.yml has no services section.');

  const starts = [];
  for (let index = servicesStart + 1; index < lines.length; index += 1) {
    if (/^[a-zA-Z0-9_-]+:/.test(lines[index])) break;
    const match = lines[index].match(/^ {2}([a-zA-Z0-9_-]+):\s*$/);
    if (match) starts.push({ name: match[1], index });
  }

  return starts.map((service, index) => {
    const next =
      starts[index + 1]?.index ??
      lines.findIndex((line, lineIndex) => {
        return lineIndex > service.index && /^[a-zA-Z0-9_-]+:/.test(line);
      });
    const end = next < 0 ? lines.length : next;
    const block = lines.slice(service.index + 1, end).join('\n');
    const image = block.match(/^ {4}image:\s*(.+)$/m)?.[1];
    const target = block.match(/^ {6}target:\s*(.+)$/m)?.[1];

    return {
      name: service.name,
      image: image ?? (target ? 'local build' : '未声明'),
      target: target ?? '',
      ports: sectionEntries(block, 'ports'),
      volumes: sectionEntries(block, 'volumes'),
      dependencies: dependencyEntries(block),
      healthcheck: /^ {4}healthcheck:/m.test(block),
      readOnly: /^ {4}read_only:\s*true/m.test(block),
    };
  });
}

function parseNamedVolumes() {
  const source = readRepositoryFile('docker-compose.yml');
  const lines = source.split(/\r?\n/);
  const volumesStart = lines.findIndex((line) => line === 'volumes:');
  if (volumesStart < 0) return [];

  const volumes = [];
  for (const line of lines.slice(volumesStart + 1)) {
    if (line && !line.startsWith('  ')) break;
    const match = line.match(/^ {2}([a-zA-Z0-9_-]+):/);
    if (match) volumes.push(match[1]);
  }
  return volumes;
}

function renderComposeServices() {
  const services = parseComposeServices();
  const volumes = parseNamedVolumes();
  const rows = services
    .map((service) => {
      const runtime = service.target ? `${service.image}; target=${service.target}` : service.image;
      const ports = service.ports.length ? service.ports.join('<br>') : '仅容器网络';
      const dependencies = service.dependencies.length ? service.dependencies.join(', ') : '—';
      const persistence = service.volumes.length ? service.volumes.join('<br>') : '—';
      const protections = [
        service.healthcheck ? 'healthcheck' : '',
        service.readOnly ? 'read-only' : '',
      ]
        .filter(Boolean)
        .join(', ');
      return `| ${inlineCode(service.name)} | ${escapeTableCell(runtime)} | ${escapeTableCell(ports)} | ${escapeTableCell(dependencies)} | ${escapeTableCell(persistence)} | ${protections || '—'} |`;
    })
    .join('\n');

  return `${generatedHeader('Docker Compose 服务', ['docker-compose.yml', 'Dockerfile'])}
## 服务

<!-- prettier-ignore -->
| Service | Image / Build Target | 发布端口 | depends_on | Volume Mount | 运行保护 |
| --- | --- | --- | --- | --- | --- |
${rows}

## Named Volumes

${volumes.length ? volumes.map((volume) => `- ${inlineCode(volume)}`).join('\n') : '- 当前没有 Named Volume。'}

\`depends_on\` 只呈现声明关系；启动条件、健康语义和故障恢复方式仍需阅读 Compose 原文及教程解释。
`;
}

function namedBlocks(source, kind) {
  const expression = new RegExp(`^${kind}\\s+(\\w+)\\s*\\{([\\s\\S]*?)^\\}`, 'gm');
  return [...source.matchAll(expression)].map((match) => ({
    name: match[1],
    body: match[2].trim(),
  }));
}

function parsePrismaFields(body) {
  return body
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('//') && !line.startsWith('@@'))
    .map((line) => {
      const [name, type, ...attributes] = line.split(/\s+/);
      return { name, type, attributes: attributes.join(' ') || '—' };
    });
}

function parsePrismaDirectives(body) {
  return body
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith('@@'));
}

function prismaTableName(model) {
  return model.body.match(/@@map\("([^"]+)"\)/)?.[1] ?? model.name;
}

function prismaMigrations() {
  const directory = repositoryPath('prisma/migrations');
  if (!existsSync(directory)) return [];

  return readdirSync(directory)
    .filter((name) => {
      const path = join(directory, name);
      return statSync(path).isDirectory() && existsSync(join(path, 'migration.sql'));
    })
    .sort();
}

function renderPrismaModels() {
  const source = readRepositoryFile('prisma/schema.prisma');
  const models = namedBlocks(source, 'model');
  const enums = namedBlocks(source, 'enum');
  const migrations = prismaMigrations();
  const provider = source.match(/datasource\s+\w+\s*\{[\s\S]*?provider\s*=\s*"([^"]+)"/)?.[1];
  const generator = source.match(/generator\s+\w+\s*\{[\s\S]*?provider\s*=\s*"([^"]+)"/)?.[1];

  const enumSections = enums
    .map((entry) => {
      const values = entry.body
        .split(/\r?\n/)
        .map((line) => line.trim())
        .filter((line) => line && !line.startsWith('//'));
      return `### ${entry.name}\n\n${values.map((value) => `- ${inlineCode(value)}`).join('\n')}`;
    })
    .join('\n\n');

  const modelSections = models
    .map((model) => {
      const directives = parsePrismaDirectives(model.body);
      const fields = parsePrismaFields(model.body)
        .map(
          (field) =>
            `| ${inlineCode(field.name)} | ${inlineCode(field.type)} | ${escapeTableCell(field.attributes)} |`,
        )
        .join('\n');
      return `### ${model.name} → ${inlineCode(prismaTableName(model))}

Model Directives：${directives.length ? directives.map((directive) => inlineCode(directive)).join('、') : '—'}

<!-- prettier-ignore -->
| Field | Prisma Type | Attributes / Relation |
| --- | --- | --- |
${fields}`;
    })
    .join('\n\n');

  const migrationRows = migrations
    .map((name) => {
      const path = `prisma/migrations/${name}/migration.sql`;
      return `| ${inlineCode(name)} | ${repositoryLink(path, 'migration.sql')} |`;
    })
    .join('\n');

  return `${generatedHeader('Prisma 数据模型与迁移', ['prisma/schema.prisma', 'prisma/migrations'])}
- Datasource Provider：${inlineCode(provider ?? '未识别')}
- Client Generator：${inlineCode(generator ?? '未识别')}
- Models：${models.length}
- Enums：${enums.length}
- Migrations：${migrations.length}

## Enums

${enumSections || '当前没有 Enum。'}

## Models

${modelSections || '当前没有 Model。'}

## Migration 历史

<!-- prettier-ignore -->
| Migration | SQL |
| --- | --- |
${migrationRows || '| — | — |'}
`;
}

function joinUrlParts(...parts) {
  const normalized = parts
    .filter((part) => part !== undefined && part !== null && part !== '')
    .map((part) => String(part).replace(/^\/+|\/+$/g, ''))
    .filter(Boolean);
  return `/${normalized.join('/')}`;
}

function renderApiRoutes() {
  const prefixSource = readRepositoryFile('apps/api/src/configure-application.ts');
  const prefix = prefixSource.match(/setGlobalPrefix\(\s*['"]([^'"]+)['"]\s*\)/)?.[1] ?? '';
  const controllerFiles = walkFiles(repositoryPath('apps/api/src'), (path) =>
    path.endsWith('.controller.ts'),
  );
  const routes = [];

  for (const file of controllerFiles) {
    const source = readFileSync(file, 'utf8');
    const basePath = source.match(/@Controller\(\s*(?:['"`]([^'"`]*)['"`])?\s*\)/)?.[1] ?? '';
    const controller =
      source.match(/export\s+class\s+(\w+Controller)\b/)?.[1] ?? 'UnknownController';
    const expression =
      /@(Get|Post|Put|Patch|Delete|Options|Head)\s*\(\s*(?:['"`]([^'"`]*)['"`])?\s*\)/g;
    for (const match of source.matchAll(expression)) {
      routes.push({
        method: match[1].toUpperCase(),
        path: joinUrlParts(prefix, basePath, match[2]),
        controller,
        file: toPosix(relative(repositoryRoot, file)),
      });
    }
  }

  routes.sort(
    (left, right) => left.path.localeCompare(right.path) || left.method.localeCompare(right.method),
  );

  const moduleFiles = walkFiles(repositoryPath('apps/api/src'), (path) =>
    path.endsWith('.module.ts'),
  );
  const modules = moduleFiles
    .map((file) => {
      const source = readFileSync(file, 'utf8');
      return {
        name: source.match(/export\s+class\s+(\w+Module)\b/)?.[1] ?? 'UnknownModule',
        file: toPosix(relative(repositoryRoot, file)),
      };
    })
    .sort((left, right) => left.name.localeCompare(right.name));

  const routeRows = routes
    .map(
      (route) =>
        `| ${inlineCode(route.method)} | ${inlineCode(route.path)} | ${route.controller} | ${repositoryLink(route.file, route.file)} |`,
    )
    .join('\n');
  const moduleRows = modules
    .map((module) => `| ${module.name} | ${repositoryLink(module.file, module.file)} |`)
    .join('\n');

  return `${generatedHeader('NestJS 模块与 API 路由', [
    'apps/api/src',
    'apps/api/src/configure-application.ts',
  ])}
生成器静态读取 \`@Controller\` 和 HTTP Method Decorator。动态路由、运行时 Module 或 Adapter 行为仍需通过 OpenAPI/E2E 验证。

## Modules

<!-- prettier-ignore -->
| Module | Source |
| --- | --- |
${moduleRows || '| — | — |'}

## Routes

全局 Prefix：${inlineCode(joinUrlParts(prefix))}

<!-- prettier-ignore -->
| Method | Route | Controller | Source |
| --- | --- | --- | --- |
${routeRows || '| — | — | — | — |'}
`;
}

export function renderProjectFacts() {
  return new Map([
    [`${generatedDirectory}/README.md`, renderGeneratedIndex()],
    [`${generatedDirectory}/commands.md`, renderCommands()],
    [`${generatedDirectory}/environment.md`, renderEnvironment()],
    [`${generatedDirectory}/compose-services.md`, renderComposeServices()],
    [`${generatedDirectory}/prisma-models.md`, renderPrismaModels()],
    [`${generatedDirectory}/api-routes.md`, renderApiRoutes()],
  ]);
}
